config/routes.rb
Inventory::Application.routes.draw do
  resources :devices

  resources :cabinets

end

app/models/cabinet.rb
class Cabinet < ActiveRecord::Base
    has_many :devices
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :cabinet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
  before_action :set_cabinet, only: [:show, :edit, :update, :destroy]

  # GET /cabinets
  # GET /cabinets.json
  def index
    @cabinets = Cabinet.all
  end

  # GET /cabinets/1
  # GET /cabinets/1.json
  def show
  end

  # GET /cabinets/new
  def new
    @cabinet = Cabinet.new
  end

  # GET /cabinets/1/edit
  def edit
  end

  # POST /cabinets
  # POST /cabinets.json
  def create
    @cabinet = Cabinet.new(cabinet_params)

    respond_to do |format|
      if @cabinet.save
        format.html { redirect_to @cabinet, notice: 'Cabinet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cabinet }
      else
        format.html { render action: 'new' }
        format.json { render json: @cabinet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabinets/1
  # PATCH/PUT /cabinets/1.json
  def update
    respond_to do |format|
      if @cabinet.update(cabinet_params)
        format.html { redirect_to @cabinet, notice: 'Cabinet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cabinet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabinets/1
  # DELETE /cabinets/1.json
  def destroy
    @cabinet.destroy
    respond_to do |format|
      format.html { redirect_to cabinets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabinet
      @cabinet = Cabinet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cabinet_params
      params.require(:cabinet).permit(:name, :room)
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :manufacturer, :model, :cabinet_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabinets_helper.rb
module CabinetsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/cabinets/_form.html.erb
<%= form_for(@cabinet) do |f| %>
  <% if @cabinet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cabinet.errors.count, "error") %> prohibited this cabinet from being saved:</h2>

      <ul>
      <% @cabinet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cabinets/edit.html.erb
<h1>Editing cabinet</h1>

<%= render 'form' %>

<%= link_to 'Show', @cabinet %> |
<%= link_to 'Back', cabinets_path %>

app/views/cabinets/index.html.erb
<h1>Listing cabinets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Room</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cabinets.each do |cabinet| %>
      <tr>
        <td><%= cabinet.name %></td>
        <td><%= cabinet.room %></td>
        <td><%= link_to 'Show', cabinet %></td>
        <td><%= link_to 'Edit', edit_cabinet_path(cabinet) %></td>
        <td><%= link_to 'Destroy', cabinet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cabinet', new_cabinet_path %>

app/views/cabinets/new.html.erb
<h1>New cabinet</h1>

<%= render 'form' %>

<%= link_to 'Back', cabinets_path %>

app/views/cabinets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cabinet.name %>
</p>

<p>
  <strong>Room:</strong>
  <%= @cabinet.room %>
</p>

<%= link_to 'Edit', edit_cabinet_path(@cabinet) %> |
<%= link_to 'Back', cabinets_path %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :cabinet_id %><br>
    <%= f.text_field :cabinet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Cabinet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.manufacturer %></td>
        <td><%= device.model %></td>
        <td><%= device.cabinet %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= form_for @device do |f| %>
  <%= f.label :cabinet_id %>
  <%= f.collection_select :cabinet_id, Cabinet.all, :id, :name %>
<% end %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @device.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @device.model %>
</p>

<p>
  <strong>Cabinet:</strong>
  <%= @device.cabinet %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>